package com.decoupler.integration;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Shared H2 in-memory database setup for integration tests.
 *
 * <p>Only the monolith database is created here. Each {@link com.decoupler.impl.sql.SqlTableFragment}
 * creates and seeds its own isolated H2 database during {@code init()} via
 * {@link com.decoupler.impl.sql.JdbcTableReplicator}.
 *
 * <h2>E-Commerce schema</h2>
 * <pre>
 *   categories (id, name)
 *   products   (id, name, description, price, category_id)
 *   customers  (id, name, email)
 *   orders     (id, customer_id, total_amount, status, created_at)
 *   order_items(id, order_id, product_id, quantity, unit_price)
 * </pre>
 */
public class ECommerceSchemaSetup {

    public static DataSource createMonolithDataSource() {
        return createH2DataSource("monolith2");
    }

    public static DataSource createMonolithDataSource(String dbName) {
        return createH2DataSource(dbName);
    }

    private static DataSource createH2DataSource(String dbName) {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:" + dbName + ";DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        ds.setUser("sa");
        ds.setPassword("");
        return ds;
    }

    public static void setup(DataSource monolithDs) throws SQLException {
        createSchema(monolithDs);
        seedData(monolithDs);
    }

    public static void teardown(DataSource monolithDs) throws SQLException {
        dropSchema(monolithDs);
    }

    static void createSchema(DataSource ds) throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("""
                CREATE TABLE IF NOT EXISTS categories (
                    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS products (
                    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name        VARCHAR(200) NOT NULL,
                    description VARCHAR(500),
                    price       DECIMAL(10,2) NOT NULL,
                    category_id INTEGER NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS customers (
                    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name  VARCHAR(200) NOT NULL,
                    email VARCHAR(200) NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id  INTEGER NOT NULL,
                    total_amount DECIMAL(10,2) NOT NULL,
                    status       VARCHAR(50) NOT NULL,
                    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS order_items (
                    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id    INTEGER NOT NULL,
                    product_id  INTEGER NOT NULL,
                    quantity    INTEGER NOT NULL,
                    unit_price  DECIMAL(10,2) NOT NULL
                )
                """);
        }
    }

    static void dropSchema(DataSource ds) throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("DROP TABLE IF EXISTS order_items");
            st.execute("DROP TABLE IF EXISTS orders");
            st.execute("DROP TABLE IF EXISTS customers");
            st.execute("DROP TABLE IF EXISTS products");
            st.execute("DROP TABLE IF EXISTS categories");
        }
    }

    static void seedData(DataSource ds) throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("INSERT INTO categories (id, name) VALUES (1, 'Electronics')");

            st.execute("INSERT INTO products (id, name, description, price, category_id) VALUES " +
                    "(1, 'Laptop',     'High-performance laptop',    999.99, 1)");
            st.execute("INSERT INTO products (id, name, description, price, category_id) VALUES " +
                    "(2, 'Phone',      'Latest smartphone',          499.99, 1)");
            st.execute("INSERT INTO products (id, name, description, price, category_id) VALUES " +
                    "(3, 'Headphones', 'Noise-cancelling headphones', 149.99, 1)");

            st.execute("INSERT INTO customers (id, name, email) VALUES (1, 'Alice', 'alice@example.com')");
            st.execute("INSERT INTO customers (id, name, email) VALUES (2, 'Bob',   'bob@example.com')");

            st.execute("INSERT INTO orders (id, customer_id, total_amount, status) VALUES " +
                    "(1, 1, 1499.98, 'PAID')");
            st.execute("INSERT INTO orders (id, customer_id, total_amount, status) VALUES " +
                    "(2, 2, 149.99, 'PENDING')");

            st.execute("INSERT INTO order_items (id, order_id, product_id, quantity, unit_price) VALUES " +
                    "(1, 1, 1, 1, 999.99)");
            st.execute("INSERT INTO order_items (id, order_id, product_id, quantity, unit_price) VALUES " +
                    "(2, 1, 2, 1, 499.99)");
            st.execute("INSERT INTO order_items (id, order_id, product_id, quantity, unit_price) VALUES " +
                    "(3, 2, 3, 1, 149.99)");

            st.execute("ALTER TABLE categories   ALTER COLUMN id RESTART WITH 100");
            st.execute("ALTER TABLE products     ALTER COLUMN id RESTART WITH 100");
            st.execute("ALTER TABLE customers    ALTER COLUMN id RESTART WITH 100");
            st.execute("ALTER TABLE orders       ALTER COLUMN id RESTART WITH 100");
            st.execute("ALTER TABLE order_items  ALTER COLUMN id RESTART WITH 100");
        }
    }
}
