package com.decoupler.impl.decomposition;

import java.util.List;

/**
 * A decomposition plan generated by the LLM for a specific transaction pattern.
 *
 * <p>Jackson POJO: requires a no-arg constructor plus getters/setters.
 */
public class DecompositionPlan {

    private String queryPattern;
    private String type; // "READ" or "WRITE"
    private List<PlanStep> steps;
    private String leafStep;
    private List<String> resultColumns;

    public DecompositionPlan() {}

    public String getQueryPattern() { return queryPattern; }
    public void setQueryPattern(String queryPattern) { this.queryPattern = queryPattern; }

    public String getType() { return type; }
    public void setType(String type) { this.type = type; }

    public List<PlanStep> getSteps() { return steps; }
    public void setSteps(List<PlanStep> steps) { this.steps = steps; }

    public String getLeafStep() { return leafStep; }
    public void setLeafStep(String leafStep) { this.leafStep = leafStep; }

    public List<String> getResultColumns() { return resultColumns; }
    public void setResultColumns(List<String> resultColumns) { this.resultColumns = resultColumns; }

    @Override
    public String toString() {
        return "DecompositionPlan{queryPattern='" + queryPattern + "', type='" + type
                + "', steps=" + steps + '}';
    }
}
