package com.decoupler.impl.decomposition;

import com.decoupler.impl.sql.SqlInsertCommand;
import com.decoupler.impl.sql.SqlPartition;
import com.decoupler.impl.sql.SqlReadCommand;
import com.decoupler.impl.sql.SqlTableFragment;
import com.decoupler.impl.sql.SqlTransaction;
import com.decoupler.interfaces.Fragment;
import com.decoupler.interfaces.Partition;
import com.decoupler.interfaces.Result;
import com.decoupler.interfaces.Transaction;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.*;

class PlanInterpreterTest {

    static DataSource ds;
    static SqlTableFragment ordersFragment;
    static SqlTableFragment itemsFragment;
    static Partition partition;

    @BeforeAll
    static void setUpAll() throws SQLException {
        JdbcDataSource jds = new JdbcDataSource();
        jds.setURL("jdbc:h2:mem:plan_interp_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        jds.setUser("sa");
        jds.setPassword("");
        ds = jds;

        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id INTEGER NOT NULL,
                    status      VARCHAR(50) NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS order_items (
                    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id   INTEGER NOT NULL,
                    product    VARCHAR(100) NOT NULL
                )
                """);
            st.execute("INSERT INTO orders (id, customer_id, status) VALUES (1, 42, 'PAID')");
            st.execute("INSERT INTO orders (id, customer_id, status) VALUES (2, 99, 'PENDING')");
            st.execute("INSERT INTO order_items (order_id, product) VALUES (1, 'Laptop')");
            st.execute("INSERT INTO order_items (order_id, product) VALUES (1, 'Phone')");
            st.execute("ALTER TABLE orders       ALTER COLUMN id RESTART WITH 100");
            st.execute("ALTER TABLE order_items  ALTER COLUMN id RESTART WITH 100");
        }

        ordersFragment = new SqlTableFragment(ds, "orders");
        itemsFragment = new SqlTableFragment(ds, "order_items");
        partition = new SqlPartition(
                List.of(ordersFragment, itemsFragment),
                List.of(new SqlReadCommand(Map.of()), new SqlInsertCommand(Map.of()))
        );
    }

    @AfterAll
    static void tearDownAll() throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("DROP TABLE IF EXISTS order_items");
            st.execute("DROP TABLE IF EXISTS orders");
        }
    }

    private static Transaction tx(String id, Object... params) {
        return SqlTransaction.of(id, "irrelevant", params);
    }

    @Test
    void singleReadStepReturnsRowsFromOneFragment() {
        DecompositionPlan plan = new DecompositionPlan();
        plan.setQueryPattern("find_orders");
        plan.setType("READ");

        PlanStep step = new PlanStep();
        step.setId("s1");
        step.setType(PlanStepType.READ);
        step.setFragment("orders");
        step.setFilter(Map.of("customer_id", "$0"));
        plan.setSteps(List.of(step));

        PlanInterpreter interp = new PlanInterpreter();
        Result r = interp.execute(tx("find_orders", 42), plan, partition);

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) r.message();
        assertThat(rows).hasSize(1);
        assertThat(((Number) rows.get(0).get("customer_id")).intValue()).isEqualTo(42);
    }

    @Test
    void nestedReadJoinsTwoFragments() {
        DecompositionPlan plan = new DecompositionPlan();
        plan.setQueryPattern("orders_with_items");
        plan.setType("READ");

        PlanStep root = new PlanStep();
        root.setId("s1");
        root.setType(PlanStepType.READ);
        root.setFragment("orders");
        root.setFilter(Map.of("customer_id", "$0"));

        PlanStep child = new PlanStep();
        child.setId("s2");
        child.setType(PlanStepType.READ);
        child.setFragment("order_items");
        child.setFilter(Map.of("order_id", "$s1.id"));
        child.setParent("s1");

        plan.setSteps(List.of(root, child));

        PlanInterpreter interp = new PlanInterpreter();
        Result r = interp.execute(tx("orders_with_items", 42), plan, partition);

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) r.message();
        assertThat(rows).hasSize(2);
        rows.forEach(row -> assertThat(row).containsKey("product"));
    }

    @Test
    void singleInsertStepInsertsRowAndReturnsCount() throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("DELETE FROM orders WHERE status = 'INSERTED_BY_TEST'");
        }

        DecompositionPlan plan = new DecompositionPlan();
        plan.setQueryPattern("insert_order");
        plan.setType("WRITE");

        PlanStep step = new PlanStep();
        step.setId("s1");
        step.setType(PlanStepType.INSERT);
        step.setFragment("orders");
        step.setValues(Map.of("customer_id", "$0", "status", "$1"));
        plan.setSteps(List.of(step));

        PlanInterpreter interp = new PlanInterpreter();
        Result r = interp.execute(tx("insert_order", 7, "INSERTED_BY_TEST"), plan, partition);

        assertThat(r.message()).isEqualTo(1);

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>)
                ordersFragment.execute(new SqlReadCommand(Map.of("status", "INSERTED_BY_TEST"))).message();
        assertThat(rows).hasSize(1);
    }
}
