package com.decoupler.impl.sql;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Shared H2 setup for command unit tests.
 *
 * <p>Each test class uses a uniquely named in-memory database so tests can run in parallel
 * without interference.
 */
public final class H2TestSupport {

    private H2TestSupport() {}

    public static DataSource createDataSource(String dbName) {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:" + dbName + ";DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        ds.setUser("sa");
        ds.setPassword("");
        return ds;
    }

    public static void createItemsTable(DataSource ds) throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("""
                CREATE TABLE IF NOT EXISTS items (
                    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    amt  INTEGER NOT NULL
                )
                """);
        }
    }

    public static void dropItemsTable(DataSource ds) throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("DROP TABLE IF EXISTS items");
        }
    }

    public static void insertRow(DataSource ds, String name, int amt) throws SQLException {
        try (Connection conn = ds.getConnection(); Statement st = conn.createStatement()) {
            st.execute("INSERT INTO items (name, amt) VALUES ('" + name + "', " + amt + ")");
        }
    }

    public static int countRows(DataSource ds) throws SQLException {
        try (Connection conn = ds.getConnection();
             var ps = conn.prepareStatement("SELECT COUNT(*) FROM items");
             var rs = ps.executeQuery()) {
            return rs.next() ? rs.getInt(1) : 0;
        }
    }
}
