package com.decoupler.impl.sql;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * {@link FragmentReplicator} that copies a single table from a source JDBC DataSource
 * into a target DataSource by introspecting column metadata, generating CREATE TABLE DDL,
 * and bulk-inserting all rows.
 */
public class JdbcTableReplicator implements FragmentReplicator {

    private final DataSource source;

    public JdbcTableReplicator(DataSource source) {
        this.source = source;
    }

    @Override
    public void replicate(DataSource target, String tableName) {
        try {
            List<ColumnMeta> columns = introspectColumns(tableName);
            createTable(target, tableName, columns);
            copyRows(target, tableName, columns);
        } catch (SQLException e) {
            throw new RuntimeException("Replication failed for table '" + tableName + "'", e);
        }
    }

    // -------------------------------------------------------------------------
    // Schema introspection
    // -------------------------------------------------------------------------

    private List<ColumnMeta> introspectColumns(String tableName) throws SQLException {
        List<ColumnMeta> cols = new ArrayList<>();
        try (Connection conn = source.getConnection()) {
            String schema = conn.getSchema();
            DatabaseMetaData meta = conn.getMetaData();
            try (ResultSet rs = meta.getColumns(null, schema, tableName.toUpperCase(), null)) {
                while (rs.next()) {
                    cols.add(new ColumnMeta(
                            rs.getString("COLUMN_NAME"),
                            rs.getInt("DATA_TYPE"),
                            rs.getString("TYPE_NAME"),
                            rs.getInt("COLUMN_SIZE"),
                            rs.getInt("DECIMAL_DIGITS"),
                            rs.getInt("NULLABLE") != DatabaseMetaData.columnNoNulls,
                            "YES".equalsIgnoreCase(rs.getString("IS_AUTOINCREMENT"))
                    ));
                }
            }
        }
        if (cols.isEmpty()) {
            throw new IllegalStateException("Table '" + tableName + "' not found in source");
        }
        return cols;
    }

    // -------------------------------------------------------------------------
    // DDL generation
    // -------------------------------------------------------------------------

    private void createTable(DataSource target, String tableName, List<ColumnMeta> columns)
            throws SQLException {
        StringBuilder ddl = new StringBuilder("CREATE TABLE IF NOT EXISTS ")
                .append(tableName).append(" (");
        for (int i = 0; i < columns.size(); i++) {
            ColumnMeta col = columns.get(i);
            if (i > 0) ddl.append(", ");
            ddl.append(col.name()).append(" ").append(h2TypeFor(col));
            if (col.autoIncrement()) ddl.append(" GENERATED BY DEFAULT AS IDENTITY");
            else if (!col.nullable()) ddl.append(" NOT NULL");
        }
        ddl.append(")");

        try (Connection conn = target.getConnection();
             Statement st = conn.createStatement()) {
            st.execute(ddl.toString());
        }
    }

    private String h2TypeFor(ColumnMeta col) {
        return switch (col.jdbcType()) {
            case Types.INTEGER, Types.SMALLINT, Types.TINYINT -> "INTEGER";
            case Types.BIGINT -> "BIGINT";
            case Types.DECIMAL, Types.NUMERIC ->
                    "DECIMAL(" + col.size() + "," + col.decimalDigits() + ")";
            case Types.DOUBLE, Types.FLOAT -> "DOUBLE";
            case Types.REAL -> "REAL";
            case Types.BOOLEAN, Types.BIT -> "BOOLEAN";
            case Types.TIMESTAMP, Types.TIMESTAMP_WITH_TIMEZONE -> "TIMESTAMP";
            case Types.DATE -> "DATE";
            case Types.TIME -> "TIME";
            default -> "VARCHAR(" + Math.max(col.size(), 1) + ")";
        };
    }

    // -------------------------------------------------------------------------
    // Data copy
    // -------------------------------------------------------------------------

    private void copyRows(DataSource target, String tableName, List<ColumnMeta> columns)
            throws SQLException {
        String selectSql = "SELECT * FROM " + tableName;
        String insertSql = buildInsertSql(tableName, columns);

        try (Connection src = source.getConnection();
             PreparedStatement sel = src.prepareStatement(selectSql);
             ResultSet rs = sel.executeQuery();
             Connection tgt = target.getConnection();
             PreparedStatement ins = tgt.prepareStatement(insertSql)) {

            while (rs.next()) {
                for (int i = 1; i <= columns.size(); i++) {
                    ins.setObject(i, rs.getObject(i));
                }
                ins.addBatch();
            }
            ins.executeBatch();
        }
    }

    private String buildInsertSql(String tableName, List<ColumnMeta> columns) {
        StringBuilder sb = new StringBuilder("INSERT INTO ").append(tableName).append(" (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(columns.get(i).name());
        }
        sb.append(") VALUES (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("?");
        }
        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Column metadata record
    // -------------------------------------------------------------------------

    private record ColumnMeta(String name, int jdbcType, String typeName,
                               int size, int decimalDigits, boolean nullable, boolean autoIncrement) {}
}
